name: auto_disposable_tab_bar_sample
description: Sample App using AutoDisposableTabBar

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true